### ISSUE TITLE
Add support for cross-platform targets

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#134]
Currently a target can only be associated with one platform, however a common use case is to have multiple targets per-platform from a single source set to enable that target to be consumed on multiple platforms.

This feature would enable a target to specify multiple platforms, as follows:

**YAML/JSON**
```yaml
targets:
  My framework:
    platform:
    - ios
    - tv
```

**Specfile**
```ruby
target 'My framework' do
  platform 'ios'
  platform 'tv'
end
```

This would perform a few actions within struct:

- For each platform, a target suffixed by the platform name would be generated:
  - My framework-iOS
  - My framework-tvOS
- Each target would define the preprocessor variable PLATFORM_{PLATFORM_NAME}
- Each target variant would share the same source set, the source set group will retain the original target's name

**Todo:**
- [x] Parsing for platform-scoped configurations
- [x] Parsing for platform-scoped references
- [x] Parsing for platform-scoped variant configurations
- [x] Parsing for platform-scoped variant references
- [x] Parsing for platform-scoped i18n-resources
- [x] Parsing for platform-scoped variant i18n-resources
- [x] Parsing for more than one platform
- [x] Preprocessing to resolve platform-scoped targets into multiple targets

**Comment by yonaskolb** [comment]
Great solution! Much better than currently defining duplicate targets with differing platforms. One wrinkle though would be how to reference Carthage dependancies as they are build per platform `- location: Carthage/Build/tvOS/BrightFutures.framework`. Another problem would be if that cross platform "target" referenced another cross platform "target". Struct would need to intelligently get it to reference the correct actual target.
Once possible solution is to have some sort of `platformTargets` list that acts a bit like a variant where you can specify overrides per platform that get used in the actually created target.

**Comment by lyptt** [comment]
Hi @yonaskolb, yes we'll have to come up with a mechanism to only link to a specific platform's frameworks. Potentially we could namespace the references when using multiple platforms, for example:

```yaml
targets:
  My framework:
    platform:
    - ios
    - tv
    references:
      ios:
      - location: Carthage/Build/iOS/BrightFutures.framework
      tv
      - location: Carthage/Build/tvOS/BrightFutures.framework
```

**Comment by yonaskolb** [comment]
Or some sort of substitution system using mustache `{{ platform }}`, xcconfig style `${platform}`/`$(platform)`, yaml referencing, or any other style:
```
targets:
  My framework:
    platform:
    - ios
    - tv
    references:
      - location: Carthage/Build/${platform}/BrightFutures.framework
```

**Comment by yonaskolb** [comment]
Generating multiple platform targets from 1 would also affect anything referencing those targets, like another target trying to pull in one of those targets as a dependancy

**Comment by lyptt** [comment]
Yes we'd have to do a platform resolution step when resolving references to ensure that the correct target is selected as a reference.

**Comment by yonaskolb** [comment]
I don't want to rush you at all, but when would you estimate something like this would be completed, along with a guesstimate of the actual 2.2.0 release?

**Comment by lyptt** [comment]
Hi @yonaskolb. I have a full day to work on this tomorrow, so I recommend keeping an eye on the project over the next couple of days.

Chances are we can get this done very soon (days rather than weeks), but certain parts will require some thought. 

Even if we don't end up releasing this week, we should still be able to get something usable in develop!

**Comment by lyptt** [comment]
@yonaskolb since you're one of the first devs that'll be using this feature, I'll mention you on the pull request when it's ready to merge. If you could provide feedback at that time, that would ensure that the implementation of this feature is enough for your needs.
